### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by OscarWoHA** [vimond/replay#30]
**Describe the bug**

Replay does not fail gracefully in the case of a NotAllowedError. 

**To Reproduce**

Steps to reproduce the behaviour:

1. Chrome for iPhone
2. Call .play() programmatically
3. See an error

**Expected behavior**

Graceful rejection of the function

**Smartphone (please complete the following information):**

 - Device: iPhone11
 - OS: iOS 14
 - Browser: Chrome for iPhone
 - Version: Unknown or not relevant

**Additional context**
- React v17
- Video stream URL: https://videodelivery.net/b3e5caf244c3b177b7e93da42af90621/manifest/video.m3u8
- HlsjsVideoStreamer

**Comment by torerikal** [comment]
Version 3.0.1, released now, changes the exposed `play()` method so that it returns the promise also returned from calling `play()` [directly](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play) on the `HTMLVideoElement`. By `await`ing or adding` .catch(err => ...)` to your play() invocation, you should be able to deal gracefully with the rejection. Since there are no other details on what error to observe, I hope this covers your case.
