### ISSUE TITLE
Adaptive bitrate with cookie support?

### ISSUE THREAD

**Issue by himanshuphirke** [vimond/replay#31]
Does this player support adaptive bitrate play of HLS/CMAF streams with cookie support?
Or signed url if it can use  
For authenticated playback

**Comment by torerikal** [comment]
Replay relies on e.g. Shaka Player or HLS.js for supporting adaptive streaming. 

You can read more about which formats and variations they support at their project pages:

https://github.com/google/shaka-player#hls-features
https://github.com/video-dev/hls.js

On how to use either HLS.js or Shaka Player through Replay, please see this documentation chapter: https://vimond.github.io/replay/#/advanced-playback/adaptive-streaming

Including cookies, adding headers, or applying URL signatures usually means the stream requests from these libraries must be intercepted and modified before they are sent. Both HLS.js and Shaka Player allows this, and in Replay's configuration you can specify such request interceptors, as documented here:
https://vimond.github.io/replay/#/advanced-playback/adaptive-streaming#intercepting-stream-requests-for-eg-header-manipulation

Replay enables using the advanced features of Shaka Player and HLS.js in React apps, but be aware that you mainly need to work with the documentation and examples for these libraries in specific, in order to implement authenticated playback.
