### ISSUE TITLE
[QUESTION] Custom aspect ratio configuration

### ISSUE THREAD

**Issue by maxsalven** [vimond/replay#57]
Is there a correct way to configure a custom aspect ratio? Specifying it in options doesn't seem to work, despite it being a supported prop:
https://github.com/vimond/replay/blob/56b98b4e2fd7abbf2799bf02a6b8bf48e5ba1e73/src/replay/default-player/types.js#L46-L49

This is still 16x9:
```
   <Replay
      source="./playlist.m3u8"
      options={{ aspectRatio: { horizontal: 1, vertical: 1 } }}
    >
    <CompoundVideoStreamer />
  </Replay>
```

**Comment by torerikal** [comment]
Hi Max,

As you have found, there was a bug where a custom aspect ratio configuration was ignored. This is now corrected, and the fix is included in a new release of `vimond-replay`, version `3.3.1`. Please upgrade and check if it addresses your requirements. You can also see the custom aspect ratio setting in action here: https://codesandbox.io/s/bold-river-3gwei8?fontsize=14&hidenavigation=1&theme=dark
